#+TITLE: Your Title Here
# #+DATE:
#+AUTHOR: yourfirstname yourlastname
#+SETUPFILE: ./.preamble.org
# Specify bibliography here because org-ref likes it this way.
#+LATEX_HEADER: \addbibresource{../bib/citations.bib}
#+EXPORT_FILE_NAME: <your-file-name-here>
@@latex:\setlength{\parindent}{0.5in}@@
@@latex:\setlength{\bibindent}{0.5in}@@

#+begin_tcolorbox
This is an assignment question.
#+end_tcolorbox

body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. body text here. [[citep:&xu-2015-relat-between 25]]

{{{bqstart}}}
This is a blockquote.
Blockquotes need to be real lengthy for them to be blockquotes.
Generally though, teachers don't want you to put too many of these in your essays becuase it makes it look like you're trying to fill up space [[citep:&xu-2015-relat-between 90]].
{{{bqend}}}

#+begin_export latex
\newpage
#+end_export
# "Work Cited" if only one work
#+begin_center
References
#+end_center
@@latex:\printbibliography[heading=none]@@
@@latex:\begin{comment}@@
[[printbibliography:]]
@@latex:\end{comment}@@
