#+OPTIONS: author:nil num:nil toc:nil
#+STARTUP: fold

* Contents :TOC:
- [[#what-is-this-repo][What is this repo?]]
- [[#usage][Usage]]
- [[#the-english-mla-template][The =english-mla= Template]]
- [[#the-general-apa-template][The =general-apa= Template]]
- [[#the-history-cmos-template][The =history-cmos= Template]]
- [[#the-science-apa-template][The =science-apa= Template]]
- [[#add-presentation-template][add presentation template]]
- [[#modify-other-templates][modify other templates]]
  - [[#add-gitignores][add gitignores]]
  - [[#add-better-directory-structure][add better directory structure]]
- [[#issues][Issues]]
- [[#license][License]]
- [[#footnotes][Footnotes]]

* What is this repo?
*NOTE: This documentation is meant to be viewed within Emacs.*

This is a repository containing various templates to make documents in different styles using Emacs [[https://orgmode.org/][org-mode]].
I try to do all my writing in org mode, and I decided that I would make my life easier by centralizing some of the skeletons that I use.
I myself am just a student, and am far from an org mode (or git/GitHub) expert, so pull requests, issues, and suggestions are welcome!
* Usage
1. ~git clone~ the repo and just copy the templates to the directory of your assignment whenever you need to.
2. Alternatively, ~curl~ or ~wget~ whatever template and (its respective preamble) you want and work that way.

Please note that these templates are optimized for PDF/LaTeX export.
You could probably still use these templates and do writing in them, and then make an ODT or a DOCX file with the default export capabilities or [[https://www.pandoc.org][pandoc]], if necessary.
You would just have to go through and fix the formatting of the document.

For citations, cross-referencing, and more, I highly recommend installing [[https://github.com/jkitchin/org-ref][org-ref]].
You can use the [[https://orgmode.org/manual/Citation-handling.html][new built-in citation system]][fn:1] for org mode (since version 9.5), but these templates are not optimized for it, as I couldn't get it to work for me yet.

Each template includes some dummy citations and a dummy BibTeX file so one can get have examples of how to cite works in org mode.
In all my templates I provide two macros called =bqstart= and =bqend=, which start and end blockquotes for LaTeX export.

You generally should not have to touch the =.preamble.org= files, but if you need customization, these are where packages are imported and page layout is setup.
*If you use pdfLaTeX to compile your documents, you will want to find your own solution for using Times New Roman font.*
I use ~fontspec~ and set the main font to Times New Roman in all but the =general-apa= template, so if you plan to use any of those templates, switch your compiler to XeLaTeX or LuaLaTeX.

Each repo has a =bib= directory, which has the CSL files for org ref, and the dummy bibliographies.
* The =english-mla= Template
This template does its best to adhere to the Purdue OWL [[https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_style_introduction.html][guidelines for the MLA style]].
Be sure to put the title of your work in the *Title* section, as the title is used to make the title of the actual document.
Alternatively, you could just type in the title in the =#+begin_center= block yourself.
The same thing goes for the date, but with the *Author* section, input your last name, as I expand a macro holding the author to have the heading with last name and page number in the top right.

There are faculties provided to auto-generate your /Works Cited/ page, but should you need to edit it, you can edit the LaTeX specific parts. For citing works, you'll usually be using ~citep~ (or maybe ~autocite~ works as well?) from org-ref.
* The =general-apa= Template
This template is for general documents that aren't required to fit any style.
It's named "general-apa" because should you /need/ to include the occasional citation or bibliography, this template can do so according to APA format [[https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_style_introduction.html][according to the Purdue OWL]].

This template will make a title for you on your final LaTeX PDF, so make sure you include your title, name, and date.
Alternatively, you can toggle those off in the =.preamble.org= file.
Page numbers are included at the bottom center of your document.
Margins are 1 inch all around.
You can use =#+begin_tcolorbox= and =#+end_tcolorbox= blocks put colored boxes around sentences (LaTeX export only).
* The =history-cmos= Template
This template does its best to adhere to the Purdue OWL [[https://owl.purdue.edu/owl/research_and_citation/chicago_manual_17th_edition/cmos_formatting_and_style_guide/chicago_manual_of_style_17th_edition.html][guidelines for the Chicago Manual of Style, 17th ed]] (notes-bibliography).
I use macro expansion with this template also, so be sure to put your name, title of your work, and the date in the proper sections.
I don't normally have to make bibliographies with my CMoS papers, so if you need faculties for that you would have to add them yourself, or submit a pull request.

Use ~autocite~ with org-ref to get the proper notes-bibliography citation style.
* The =science-apa= Template
This template does not differ much from the =general-apa= template. I don't provide the same tcolorbox environment though, and this is meant more so to typeset small assignments for a science class.
* TODO add presentation template
* TODO modify other templates
** TODO add gitignores
** DONE add better directory structure
CLOSED: [2021-12-19 Sun 14:32]
* Issues
I still haven't found a good way to implement the blockquotes in org-mode where they only indent on the left.
If anyone can find out a way to do so, I'd greatly appreciate a pull request.
* License
See [[./LICENSE][this document]] with the info.
* Footnotes
[fn:1] See also: [[https://www.orgmode.org/Changes.html][the release notes]] and [[https://blog.tecosaur.com/tmio/2021-07-31-citations.html][this blog post]].
